"""
Core module - exceptions, constants, and security utilities.
"""

from src.core.exceptions import (
    AgentError,
    BlockedError,
    DatabaseError,
    DuplicateRecordError,
    EmailDeliveryError,
    InvalidURLError,
    ModelError,
    NetworkError,
    NotFoundError,
    NotificationError,
    ParseError,
    PerpeeError,
    PriceValidationError,
    PrivateIPError,
    RateLimitError,
    RecordNotFoundError,
    RobotsBlockedError,
    ScraperError,
    StructureChangeError,
    TimeoutError,
    TokenLimitError,
    ToolExecutionError,
    UnsupportedStoreError,
    URLError,
    ValidationError,
)
from src.core.security import (
    extract_domain,
    is_private_ip,
    is_whitelisted_store,
    normalize_price,
    resolve_and_validate_url,
    sanitize_html,
    sanitize_product_name,
    sanitize_text,
    validate_price,
    validate_url,
    validate_whitelisted_url,
)

__all__ = [
    # Exceptions
    "AgentError",
    "BlockedError",
    "DatabaseError",
    "DuplicateRecordError",
    "EmailDeliveryError",
    "InvalidURLError",
    "ModelError",
    "NetworkError",
    "NotFoundError",
    "NotificationError",
    "ParseError",
    "PerpeeError",
    "PriceValidationError",
    "PrivateIPError",
    "RateLimitError",
    "RecordNotFoundError",
    "RobotsBlockedError",
    "ScraperError",
    "StructureChangeError",
    "TimeoutError",
    "TokenLimitError",
    "ToolExecutionError",
    "UnsupportedStoreError",
    "URLError",
    "ValidationError",
    # Security
    "extract_domain",
    "is_private_ip",
    "is_whitelisted_store",
    "normalize_price",
    "resolve_and_validate_url",
    "sanitize_html",
    "sanitize_product_name",
    "sanitize_text",
    "validate_price",
    "validate_url",
    "validate_whitelisted_url",
]
