"""initial_tables

Revision ID: 43eb54068552
Revises:
Create Date: 2026-01-08 12:30:30.464196

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43eb54068552'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('upc', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canonical_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canonical_products_upc'), ['upc'], unique=False)

    op.create_table('stores',
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_whitelisted', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('selectors', sa.JSON(), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('domain')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('store_domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('upc', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ERROR', 'NEEDS_ATTENTION', 'PRICE_UNAVAILABLE', 'ARCHIVED', name='productstatus'), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('canonical_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['canonical_products.id'], ),
    sa.ForeignKeyConstraint(['store_domain'], ['stores.domain'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_store_domain'), ['store_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_url'), ['url'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('TARGET_PRICE', 'PERCENT_DROP', 'ANY_CHANGE', 'BACK_IN_STOCK', name='alerttype'), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('min_change_threshold', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_triggered', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_product_id'), ['product_id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_scraped_at'), ['scraped_at'], unique=False)

    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('store_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_domain'], ['stores.domain'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_store_domain'), ['store_domain'], unique=False)

    op.create_table('scrape_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('strategy_used', sa.Enum('JSON_LD', 'CSS_SELECTOR', 'XPATH', 'LLM', name='extractionstrategy'), nullable=True),
    sa.Column('error_type', sa.Enum('NETWORK_ERROR', 'TIMEOUT', 'BLOCKED', 'PARSE_FAILURE', 'PRICE_VALIDATION', 'STRUCTURE_CHANGE', 'NOT_FOUND', 'ROBOTS_BLOCKED', name='scrapeerrortype'), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_logs_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_logs_scraped_at'), ['scraped_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', name='notificationchannel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_product_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_alert_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('scrape_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_logs_scraped_at'))
        batch_op.drop_index(batch_op.f('ix_scrape_logs_product_id'))

    op.drop_table('scrape_logs')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_store_domain'))
        batch_op.drop_index(batch_op.f('ix_schedules_product_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_scraped_at'))
        batch_op.drop_index(batch_op.f('ix_price_history_product_id'))

    op.drop_table('price_history')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_product_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_url'))
        batch_op.drop_index(batch_op.f('ix_products_store_domain'))

    op.drop_table('products')
    op.drop_table('stores')
    with op.batch_alter_table('canonical_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canonical_products_upc'))

    op.drop_table('canonical_products')
    # ### end Alembic commands ###
